#!/bin/sh
#
# $FreeBSD$
#
# PROVIDE: giteria
# REQUIRE: NETWORKING SYSLOG
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable giteria:
#
#giteria_enable="YES"

. /etc/rc.subr

name="giteria"
rcvar="giteria_enable"

load_rc_config $name

: ${giteria_user:="git"}
: ${giteria_enable:="NO"}
: ${giteria_directory:="/var/lib/giteria"}

command="/usr/local/bin/giteria web -c /etc/giteria/app.ini"
procname="$(echo $command |cut -d' ' -f1)"

pidfile="${giteria_directory}/${name}.pid"

start_cmd="${name}_start"
stop_cmd="${name}_stop"

giteria_start() {
	cd ${giteria_directory}
	export USER=${giteria_user}
	export HOME=/usr/home/${giteria_user}
	export GITERIA_WORK_DIR=${giteria_directory}
	/usr/sbin/daemon -f -u ${giteria_user} -p ${pidfile} $command
}

giteria_stop() {
	if [ ! -f $pidfile ]; then
		echo "GITERIA PID File not found. Maybe GITERIA is not running?"
	else
		kill $(cat $pidfile)
	fi
}

run_rc_command "$1"
