#!/bin/bash

#############################################################################
# This script sets some defaults for giteria to run in a FHS compliant manner #
#############################################################################

# It assumes that you place this script as giteria in /usr/bin
#
# And place the original in /usr/lib/giteria with working files in /var/lib/giteria
# and main configuration in /etc/giteria/app.ini
GITERIA="/usr/lib/giteria/giteria"
WORK_DIR="/var/lib/giteria"
APP_INI="/etc/gitea/app.ini"

APP_INI_SET=""
for i in "$@"; do
	case "$i" in
	"-c")
		APP_INI_SET=1
		;;
	"-c="*)
		APP_INI_SET=1
		;;
	"--config")
		APP_INI_SET=1
		;;
	"--config="*)
		APP_INI_SET=1
		;;
	*)
	;;
	esac
done

if [ -z "$APP_INI_SET" ]; then
	CONF_ARG=("-c" "${GITERIA_APP_INI:-$APP_INI}")
fi

# Provide FHS compliant defaults
GITERIA_WORK_DIR="${GITERIA_WORK_DIR:-$WORK_DIR}" exec -a "$0" "$GITERIA" "${CONF_ARG[@]}"  "$@"
