server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: aether-mailer-app
          __path__: /var/log/app/*.log

  - job_name: server-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: aether-mailer-server
          __path__: /var/log/app/server.log

  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: aether-mailer-system
          __path__: /var/log/host/*.log
