name: Aether Identity Database Release

on:
  push:
    tags: ["v*.*.*-prisma"]
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build (e.g., 1.0.0)"
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: skygenesisenterprise/aether-identity/prisma

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      package_version: ${{ steps.version.outputs.package_version }}
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Extract version from tag
        id: version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            INPUT_VERSION="${{ github.event.inputs.version }}"
            CLEAN_VERSION="${INPUT_VERSION%-prisma}"
            VERSION="v${CLEAN_VERSION#v}"
            PACKAGE_VERSION="${VERSION#v}"
          else
            TAG="${{ github.ref_name }}"
            CLEAN_VERSION="${TAG%-prisma}"
            VERSION="${CLEAN_VERSION}"
            PACKAGE_VERSION="${CLEAN_VERSION#v}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "package_version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

      - name: Verify Dockerfile exists
        run: |
          if [ -f "prisma/infra/Dockerfile" ]; then
            echo "✅ Dockerfile found at prisma/infra/Dockerfile"
          else
            echo "❌ No Dockerfile found at prisma/infra/Dockerfile"
            exit 1
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@64c9b141502b80dbbd71e008a0130ad330f480f8 # v6.18.0
        with:
          context: ./prisma
          file: ./prisma/infra/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Sign the published Docker image
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Aether Identity Prisma v${{ needs.build.outputs.package_version }}
          body: |
            ## Aether Identity Prisma v${{ needs.build.outputs.package_version }}

            🐳 **Docker Image**:
            ```
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.build.outputs.version }}
            ```

            ### Usage

            ```bash
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.build.outputs.version }}
            ```

            This image contains:
            - Prisma CLI with pnpm
            - Generated Prisma Client
            - Required dependencies for database operations

            ---
            📦 **Made with ❤️ by [Sky Genesis Enterprise](https://skygenesisenterprise.com)**
          draft: false
          prerelease: false
